In [16]:
from tensorflow.keras.preprocessing.text import one_hot

In [17]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [18]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [19]:
## Define the vocabulary size
voc_size=10000


In [20]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [21]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9964, 855, 2498, 1223],
 [9964, 855, 2498, 6520],
 [9964, 7552, 2498, 8777],
 [8685, 6113, 5570, 1927, 8961],
 [8685, 6113, 5570, 1927, 7719],
 [948, 9964, 4879, 2498, 8876],
 [3204, 9628, 3365, 1927]]

In [22]:
# Word Embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [23]:
import numpy as np

In [24]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)
# pre-padding : make the sentences of the same length (pre-zeros at first)

[[   0    0    0    0 9964  855 2498 1223]
 [   0    0    0    0 9964  855 2498 6520]
 [   0    0    0    0 9964 7552 2498 8777]
 [   0    0    0 8685 6113 5570 1927 8961]
 [   0    0    0 8685 6113 5570 1927 7719]
 [   0    0    0  948 9964 4879 2498 8876]
 [   0    0    0    0 3204 9628 3365 1927]]


In [25]:
## Feature representation

dim = 10

In [26]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

e:\projects\imdb_movie_classification_RNN\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [27]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [28]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step


array([[[ 0.03373415, -0.02095252, -0.00086046,  0.03607135,
         -0.02557394, -0.04508604, -0.01496794,  0.0170527 ,
          0.02935232,  0.00843719],
        [ 0.03373415, -0.02095252, -0.00086046,  0.03607135,
         -0.02557394, -0.04508604, -0.01496794,  0.0170527 ,
          0.02935232,  0.00843719],
        [ 0.03373415, -0.02095252, -0.00086046,  0.03607135,
         -0.02557394, -0.04508604, -0.01496794,  0.0170527 ,
          0.02935232,  0.00843719],
        [ 0.03373415, -0.02095252, -0.00086046,  0.03607135,
         -0.02557394, -0.04508604, -0.01496794,  0.0170527 ,
          0.02935232,  0.00843719],
        [ 0.00684081, -0.02513783, -0.03628725, -0.03973955,
         -0.02462511, -0.030447  ,  0.02541978,  0.03978659,
         -0.04555942, -0.04340074],
        [-0.01212946,  0.02105219,  0.04582388, -0.00628044,
          0.00524195,  0.01450062, -0.04410044, -0.02181934,
          0.03966855,  0.03097904],
        [ 0.00917978,  0.00851841,  0.03936671, -0.0

In [29]:
embedded_docs[0]

array([   0,    0,    0,    0, 9964,  855, 2498, 1223], dtype=int32)

In [34]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None